
name: Build

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Manila

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [ 'x86_64', 'aarch64' ]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            diffutils make zip pkgconf yasm nasm libtool
            bison automake autoconf wget git subversion
      - name: Setup dependencies
        shell: msys2 {0}
        run: ./setup.sh windows ${{ matrix.arch }}
      - name: Build.sh
        shell: msys2 {0}
        run: ./build.sh windows ${{ matrix.arch }}
