name: Build

on:
  push:
    branches:
      - main

env:
  TZ: Asia/Manila

jobs:
  windows:
    strategy:
      fail-fast: false
      matrix:
        config:
          [
            { sys: CLANG64, arch: x86_64 },
            { sys: CLANGARM64, arch: aarch64 }
          ]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: wget git subversion
          msystem: ${{ matrix.config.sys }}
          cache: true
      - name: Setup
        shell: msys2 {0}
        run: ./setup.sh windows ${{ matrix.config.arch }}
      - name: Build.sh
        shell: msys2 {0}
        run: ./build.sh windows ${{ matrix.config.arch }}
